# This file was generated by GoReleaser. DO NOT EDIT.
cask "itunespull" do
  version "1.0.1"

  on_macos do
    on_intel do
      sha256 "c6f94e8112c0ae56af2ea1d9823ece8e2da4163a1979e4e8ad2105462d5ee5f6"
      url "https://github.com/DrewThomasson/itunespull/releases/download/v#{version}/itunespull_Darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "418eb600b50160d06d33890a8e2628140723e21d5c3f5429b174fb8fe877662c"
      url "https://github.com/DrewThomasson/itunespull/releases/download/v#{version}/itunespull_Darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "570e1a7736945e38e502d04e096d9df2596ca12e975d1480c4024b3eaba82e54"
      url "https://github.com/DrewThomasson/itunespull/releases/download/v#{version}/itunespull_Linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "d1963d3e55cfa9b72708c88bbac291b8ae80f22cda69f93e4afef05ba7dc6658"
      url "https://github.com/DrewThomasson/itunespull/releases/download/v#{version}/itunespull_Linux_arm64.tar.gz"
    end
  end

  name "itunespull"
  desc "Stream and download music from a remote Mac running iTunes or Apple Music over SSH"
  homepage "https://github.com/DrewThomasson/itunespull"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "itunespull"

  # No zap stanza required

end
