# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Itunespull < Formula
  desc "Stream and download music from a remote Mac running iTunes or Apple Music over SSH"
  homepage "https://github.com/DrewThomasson/itunespull"
  version "1.0.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/DrewThomasson/itunespull/releases/download/v1.0.0/itunespull_Darwin_x86_64.tar.gz"
      sha256 "72e521c5a9f0bc261bc468acd061d01b84abeada4ff850c2e5c2456afd998ba1"

      define_method(:install) do
        bin.install "itunespull"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/DrewThomasson/itunespull/releases/download/v1.0.0/itunespull_Darwin_arm64.tar.gz"
      sha256 "e85200468ae76f4da0f6964801973723b40b192e02c9b4140ff0b46979088d9d"

      define_method(:install) do
        bin.install "itunespull"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/DrewThomasson/itunespull/releases/download/v1.0.0/itunespull_Linux_x86_64.tar.gz"
      sha256 "4d6d78c5e9a9c23d6dab0db18dd8731f1a1bd20cd9006e6b30fc19a649e1238b"
      define_method(:install) do
        bin.install "itunespull"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/DrewThomasson/itunespull/releases/download/v1.0.0/itunespull_Linux_arm64.tar.gz"
      sha256 "2b90c5fe610503b1a81edc8a38987caeef5ed375eabd81945be6355b7debfea1"
      define_method(:install) do
        bin.install "itunespull"
      end
    end
  end
end
