# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Itunespull < Formula
  desc "Stream and download music from a remote Mac running iTunes or Apple Music over SSH"
  homepage "https://github.com/DrewThomasson/itunespull"
  version "1.0.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/DrewThomasson/itunespull/releases/download/v1.0.1/itunespull_Darwin_x86_64.tar.gz"
      sha256 "c6f94e8112c0ae56af2ea1d9823ece8e2da4163a1979e4e8ad2105462d5ee5f6"

      define_method(:install) do
        bin.install "itunespull"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/DrewThomasson/itunespull/releases/download/v1.0.1/itunespull_Darwin_arm64.tar.gz"
      sha256 "418eb600b50160d06d33890a8e2628140723e21d5c3f5429b174fb8fe877662c"

      define_method(:install) do
        bin.install "itunespull"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/DrewThomasson/itunespull/releases/download/v1.0.1/itunespull_Linux_x86_64.tar.gz"
      sha256 "570e1a7736945e38e502d04e096d9df2596ca12e975d1480c4024b3eaba82e54"
      define_method(:install) do
        bin.install "itunespull"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/DrewThomasson/itunespull/releases/download/v1.0.1/itunespull_Linux_arm64.tar.gz"
      sha256 "d1963d3e55cfa9b72708c88bbac291b8ae80f22cda69f93e4afef05ba7dc6658"
      define_method(:install) do
        bin.install "itunespull"
      end
    end
  end
end
